services:
  - type: web
    name: content-moderation-api
    env: docker
    region: oregon
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    buildCommand: docker build -t content-moderation-api .
    port: 5656
    envVars:
      - key: PORT
        value: 5656